### ISSUE TITLE
HtmlPage

### ISSUE THREAD

**Issue by Automationer** [porscheinformatik/selenium-components#3]
Hi,

The below line of code is not working, it is requiring two parameters and I could not figure out what to pass for the second parameter
`private final HtmlPage page = new HtmlPage( "https://localhost:8080" );`

Thanks

**Comment by thred** [comment]
Thanks for your feedback. 

You have to create a `DefaultSeleniumEnvironment`. You can reuse this environment. The environment needs a `WebDriverFactory`, there are implementations called `ChromeWebDriverFactory`, `EdgeWebDriverFactory` and `FirefoxWebDriverFactory`.

So the code looks like the follwing:
```java
private final WebDriverFactory factory = new FirefoxWebDriverFactory();
prviate final SeleniumEnvironment environment = new DefaultSeleniumEnvironment(factory, "mySession");

private final HtmlPage page = new HtmlPage(environment, "https://localhost:8080" );
```
I will update the documentation as soon as possible.
